add guake terminal support
oh-my-fish/plugin-tab pull request #9
Opened 2016-11-09 16:25 UTC by mad-gooze

2016-11-09 22:36 UTC, bobthecow requested changes
Thanks! One small change.

2016-11-09 22:36 UTC, bobthecow commented on functions/tab.fish
> +      if test -n "$GUAKE_TAB_UUID"
rather than adding special handling in the `*` case, update `__tab.term_program` to detect `$GUAKE_TAB_UUID` and return `guake` :)

2016-11-09 23:01 UTC, mad-gooze commented
I got the idea!

2016-11-10 15:50 UTC, bobthecow approved these changes

2016-11-10 15:50 UTC, merged

2016-11-10 15:50 UTC, bobthecow commented
Thanks!